// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_upload

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(ctx context.Context, req *dto.UploadImageRequest) (*dto.UploadImageResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.UploadImageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UploadImageRequest) (*dto.UploadImageResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UploadImageRequest) *dto.UploadImageResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UploadImageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UploadImageRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.UploadImageRequest
func (_e *MockHandler_Expecter) Create(ctx any, req any) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockHandler_Create_Call) Run(run func(ctx context.Context, req *dto.UploadImageRequest)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UploadImageRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UploadImageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return(uploadImageResponse *dto.UploadImageResponse, err error) *MockHandler_Create_Call {
	_c.Call.Return(uploadImageResponse, err)
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(ctx context.Context, req *dto.UploadImageRequest) (*dto.UploadImageResponse, error)) *MockHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}
