// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_partymember

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, member entity.PartyMember) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.PartyMember) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, member)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.PartyMember) entity.PartyMember); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.PartyMember) error); ok {
		r1 = returnFunc(ctx, member)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - member entity.PartyMember
func (_e *MockRepository_Expecter) Create(ctx any, member any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, member)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, member entity.PartyMember)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.PartyMember
		if args[1] != nil {
			arg1 = args[1].(entity.PartyMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(partyMember entity.PartyMember, err error) *MockRepository_Create_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, member entity.PartyMember) (entity.PartyMember, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPartyIDAndUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByPartyIDAndUserID(ctx context.Context, partyID string, userID string) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, partyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPartyIDAndUserID")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, partyID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.PartyMember); ok {
		r0 = returnFunc(ctx, partyID, userID)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, partyID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByPartyIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPartyIDAndUserID'
type MockRepository_FindByPartyIDAndUserID_Call struct {
	*mock.Call
}

// FindByPartyIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - userID string
func (_e *MockRepository_Expecter) FindByPartyIDAndUserID(ctx any, partyID any, userID any) *MockRepository_FindByPartyIDAndUserID_Call {
	return &MockRepository_FindByPartyIDAndUserID_Call{Call: _e.mock.On("FindByPartyIDAndUserID", ctx, partyID, userID)}
}

func (_c *MockRepository_FindByPartyIDAndUserID_Call) Run(run func(ctx context.Context, partyID string, userID string)) *MockRepository_FindByPartyIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindByPartyIDAndUserID_Call) Return(partyMember entity.PartyMember, err error) *MockRepository_FindByPartyIDAndUserID_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockRepository_FindByPartyIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, partyID string, userID string) (entity.PartyMember, error)) *MockRepository_FindByPartyIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindPendingByUserID(ctx context.Context, userID string) ([]entity.PartyMember, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingByUserID")
	}

	var r0 []entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.PartyMember, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.PartyMember); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PartyMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindPendingByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingByUserID'
type MockRepository_FindPendingByUserID_Call struct {
	*mock.Call
}

// FindPendingByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) FindPendingByUserID(ctx any, userID any) *MockRepository_FindPendingByUserID_Call {
	return &MockRepository_FindPendingByUserID_Call{Call: _e.mock.On("FindPendingByUserID", ctx, userID)}
}

func (_c *MockRepository_FindPendingByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_FindPendingByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindPendingByUserID_Call) Return(partyMembers []entity.PartyMember, err error) *MockRepository_FindPendingByUserID_Call {
	_c.Call.Return(partyMembers, err)
	return _c
}

func (_c *MockRepository_FindPendingByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entity.PartyMember, error)) *MockRepository_FindPendingByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, id string, status entity.PartyMemberStatus) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.PartyMemberStatus) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.PartyMemberStatus) entity.PartyMember); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.PartyMemberStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status entity.PartyMemberStatus
func (_e *MockRepository_Expecter) UpdateStatus(ctx any, id any, status any) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status entity.PartyMemberStatus)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.PartyMemberStatus
		if args[2] != nil {
			arg2 = args[2].(entity.PartyMemberStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(partyMember entity.PartyMember, err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status entity.PartyMemberStatus) (entity.PartyMember, error)) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
