// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_devicetoken

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, userID string, token string, platform string) error {
	ret := _mock.Called(ctx, userID, token, platform)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, token, platform)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - token string
//   - platform string
func (_e *MockService_Expecter) Register(ctx any, userID any, token any, platform any) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, userID, token, platform)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, userID string, token string, platform string)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(err error) *MockService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, userID string, token string, platform string) error) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type MockService
func (_mock *MockService) Unregister(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockService_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) Unregister(ctx any, token any) *MockService_Unregister_Call {
	return &MockService_Unregister_Call{Call: _e.mock.On("Unregister", ctx, token)}
}

func (_c *MockService_Unregister_Call) Run(run func(ctx context.Context, token string)) *MockService_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Unregister_Call) Return(err error) *MockService_Unregister_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Unregister_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockService_Unregister_Call {
	_c.Call.Return(run)
	return _c
}
