// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_devicetoken

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteByToken provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockRepository_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRepository_Expecter) DeleteByToken(ctx any, token any) *MockRepository_DeleteByToken_Call {
	return &MockRepository_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, token)}
}

func (_c *MockRepository_DeleteByToken_Call) Run(run func(ctx context.Context, token string)) *MockRepository_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteByToken_Call) Return(err error) *MockRepository_DeleteByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockRepository_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByUserID(ctx context.Context, userID string) ([]entity.DeviceToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.DeviceToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.DeviceToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.DeviceToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.DeviceToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) FindByUserID(ctx any, userID any) *MockRepository_FindByUserID_Call {
	return &MockRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByUserID_Call) Return(deviceTokens []entity.DeviceToken, err error) *MockRepository_FindByUserID_Call {
	_c.Call.Return(deviceTokens, err)
	return _c
}

func (_c *MockRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entity.DeviceToken, error)) *MockRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(ctx context.Context, deviceToken entity.DeviceToken) error {
	ret := _mock.Called(ctx, deviceToken)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.DeviceToken) error); ok {
		r0 = returnFunc(ctx, deviceToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceToken entity.DeviceToken
func (_e *MockRepository_Expecter) Upsert(ctx any, deviceToken any) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, deviceToken)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, deviceToken entity.DeviceToken)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.DeviceToken
		if args[1] != nil {
			arg1 = args[1].(entity.DeviceToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(err error) *MockRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, deviceToken entity.DeviceToken) error) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
