// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_savedlocation

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, userID string, name string, lat float64, lng float64) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, userID, name, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, float64) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, userID, name, lat, lng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, float64) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, userID, name, lat, lng)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, float64, float64) error); ok {
		r1 = returnFunc(ctx, userID, name, lat, lng)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - lat float64
//   - lng float64
func (_e *MockService_Expecter) Create(ctx any, userID any, name any, lat any, lng any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, lat, lng)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID string, name string, lat float64, lng float64)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(savedLocation entity.SavedLocation, err error) *MockService_Create_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, name string, lat float64, lng float64) (entity.SavedLocation, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockService_Expecter) Delete(ctx any, userID any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, userID string, id string) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockService_Expecter) Get(ctx any, userID any, id any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, userID, id)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, userID string, id string)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(savedLocation entity.SavedLocation, err error) *MockService_Get_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) (entity.SavedLocation, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockService
func (_mock *MockService) ListByUserID(ctx context.Context, userID string) ([]entity.SavedLocation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.SavedLocation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.SavedLocation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SavedLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockService_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) ListByUserID(ctx any, userID any) *MockService_ListByUserID_Call {
	return &MockService_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockService_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockService_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListByUserID_Call) Return(savedLocations []entity.SavedLocation, err error) *MockService_ListByUserID_Call {
	_c.Call.Return(savedLocations, err)
	return _c
}

func (_c *MockService_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entity.SavedLocation, error)) *MockService_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID string, id string, name string, lat float64, lng float64) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, userID, id, name, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, userID, id, name, lat, lng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, userID, id, name, lat, lng)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, float64, float64) error); ok {
		r1 = returnFunc(ctx, userID, id, name, lat, lng)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - name string
//   - lat float64
//   - lng float64
func (_e *MockService_Expecter) Update(ctx any, userID any, id any, name any, lat any, lng any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, name, lat, lng)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID string, id string, name string, lat float64, lng float64)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 float64
		if args[5] != nil {
			arg5 = args[5].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(savedLocation entity.SavedLocation, err error) *MockService_Update_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, name string, lat float64, lng float64) (entity.SavedLocation, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
