// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_savedlocation

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, location entity.SavedLocation) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SavedLocation) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, location)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SavedLocation) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, location)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.SavedLocation) error); ok {
		r1 = returnFunc(ctx, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - location entity.SavedLocation
func (_e *MockRepository_Expecter) Create(ctx any, location any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, location)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, location entity.SavedLocation)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.SavedLocation
		if args[1] != nil {
			arg1 = args[1].(entity.SavedLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(savedLocation entity.SavedLocation, err error) *MockRepository_Create_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, location entity.SavedLocation) (entity.SavedLocation, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(savedLocation entity.SavedLocation, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.SavedLocation, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByUserID(ctx context.Context, userID string) ([]entity.SavedLocation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.SavedLocation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.SavedLocation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SavedLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) FindByUserID(ctx any, userID any) *MockRepository_FindByUserID_Call {
	return &MockRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByUserID_Call) Return(savedLocations []entity.SavedLocation, err error) *MockRepository_FindByUserID_Call {
	_c.Call.Return(savedLocations, err)
	return _c
}

func (_c *MockRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entity.SavedLocation, error)) *MockRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, location entity.SavedLocation) (entity.SavedLocation, error) {
	ret := _mock.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.SavedLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SavedLocation) (entity.SavedLocation, error)); ok {
		return returnFunc(ctx, location)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SavedLocation) entity.SavedLocation); ok {
		r0 = returnFunc(ctx, location)
	} else {
		r0 = ret.Get(0).(entity.SavedLocation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.SavedLocation) error); ok {
		r1 = returnFunc(ctx, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - location entity.SavedLocation
func (_e *MockRepository_Expecter) Update(ctx any, location any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, location)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, location entity.SavedLocation)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.SavedLocation
		if args[1] != nil {
			arg1 = args[1].(entity.SavedLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(savedLocation entity.SavedLocation, err error) *MockRepository_Update_Call {
	_c.Call.Return(savedLocation, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, location entity.SavedLocation) (entity.SavedLocation, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
