// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_party

import (
	"context"
	"time"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	"github.com/fark-tee/fark-tee-backend/internal/service/party"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AcceptInvite provides a mock function for the type MockService
func (_mock *MockService) AcceptInvite(ctx context.Context, actorID string, partyID string) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvite")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, actorID, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.PartyMember); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AcceptInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvite'
type MockService_AcceptInvite_Call struct {
	*mock.Call
}

// AcceptInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) AcceptInvite(ctx any, actorID any, partyID any) *MockService_AcceptInvite_Call {
	return &MockService_AcceptInvite_Call{Call: _e.mock.On("AcceptInvite", ctx, actorID, partyID)}
}

func (_c *MockService_AcceptInvite_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_AcceptInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AcceptInvite_Call) Return(partyMember entity.PartyMember, err error) *MockService_AcceptInvite_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockService_AcceptInvite_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) (entity.PartyMember, error)) *MockService_AcceptInvite_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, actorID string, name string, destinationName string, destinationLat float64, destinationLng float64, targetTime time.Time) (entity.Party, error) {
	ret := _mock.Called(ctx, actorID, name, destinationName, destinationLat, destinationLng, targetTime)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64, time.Time) (entity.Party, error)); ok {
		return returnFunc(ctx, actorID, name, destinationName, destinationLat, destinationLng, targetTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, float64, time.Time) entity.Party); ok {
		r0 = returnFunc(ctx, actorID, name, destinationName, destinationLat, destinationLng, targetTime)
	} else {
		r0 = ret.Get(0).(entity.Party)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, float64, float64, time.Time) error); ok {
		r1 = returnFunc(ctx, actorID, name, destinationName, destinationLat, destinationLng, targetTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - name string
//   - destinationName string
//   - destinationLat float64
//   - destinationLng float64
//   - targetTime time.Time
func (_e *MockService_Expecter) Create(ctx any, actorID any, name any, destinationName any, destinationLat any, destinationLng any, targetTime any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, actorID, name, destinationName, destinationLat, destinationLng, targetTime)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, actorID string, name string, destinationName string, destinationLat float64, destinationLng float64, targetTime time.Time)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 float64
		if args[5] != nil {
			arg5 = args[5].(float64)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(party entity.Party, err error) *MockService_Create_Call {
	_c.Call.Return(party, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, actorID string, name string, destinationName string, destinationLat float64, destinationLng float64, targetTime time.Time) (entity.Party, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineInvite provides a mock function for the type MockService
func (_mock *MockService) DeclineInvite(ctx context.Context, actorID string, partyID string) error {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for DeclineInvite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeclineInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineInvite'
type MockService_DeclineInvite_Call struct {
	*mock.Call
}

// DeclineInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) DeclineInvite(ctx any, actorID any, partyID any) *MockService_DeclineInvite_Call {
	return &MockService_DeclineInvite_Call{Call: _e.mock.On("DeclineInvite", ctx, actorID, partyID)}
}

func (_c *MockService_DeclineInvite_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_DeclineInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeclineInvite_Call) Return(err error) *MockService_DeclineInvite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeclineInvite_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) error) *MockService_DeclineInvite_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, actorID string, partyID string) (entity.Party, error) {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.Party, error)); ok {
		return returnFunc(ctx, actorID, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.Party); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		r0 = ret.Get(0).(entity.Party)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) Get(ctx any, actorID any, partyID any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, actorID, partyID)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(party entity.Party, err error) *MockService_Get_Call {
	_c.Call.Return(party, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) (entity.Party, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type MockService
func (_mock *MockService) Invite(ctx context.Context, actorID string, partyID string, targetUserID string) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, actorID, partyID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, actorID, partyID, targetUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) entity.PartyMember); ok {
		r0 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockService_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - targetUserID string
func (_e *MockService_Expecter) Invite(ctx any, actorID any, partyID any, targetUserID any) *MockService_Invite_Call {
	return &MockService_Invite_Call{Call: _e.mock.On("Invite", ctx, actorID, partyID, targetUserID)}
}

func (_c *MockService_Invite_Call) Run(run func(ctx context.Context, actorID string, partyID string, targetUserID string)) *MockService_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Invite_Call) Return(partyMember entity.PartyMember, err error) *MockService_Invite_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockService_Invite_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, targetUserID string) (entity.PartyMember, error)) *MockService_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type MockService
func (_mock *MockService) ListMembers(ctx context.Context, actorID string, partyID string) ([]entity.PartyMember, error) {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.PartyMember, error)); ok {
		return returnFunc(ctx, actorID, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.PartyMember); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PartyMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) ListMembers(ctx any, actorID any, partyID any) *MockService_ListMembers_Call {
	return &MockService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, actorID, partyID)}
}

func (_c *MockService_ListMembers_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListMembers_Call) Return(partyMembers []entity.PartyMember, err error) *MockService_ListMembers_Call {
	_c.Call.Return(partyMembers, err)
	return _c
}

func (_c *MockService_ListMembers_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) ([]entity.PartyMember, error)) *MockService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// MyInvites provides a mock function for the type MockService
func (_mock *MockService) MyInvites(ctx context.Context, actorID string) ([]party.Invite, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for MyInvites")
	}

	var r0 []party.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]party.Invite, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []party.Invite); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]party.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_MyInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyInvites'
type MockService_MyInvites_Call struct {
	*mock.Call
}

// MyInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
func (_e *MockService_Expecter) MyInvites(ctx any, actorID any) *MockService_MyInvites_Call {
	return &MockService_MyInvites_Call{Call: _e.mock.On("MyInvites", ctx, actorID)}
}

func (_c *MockService_MyInvites_Call) Run(run func(ctx context.Context, actorID string)) *MockService_MyInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MyInvites_Call) Return(invites []party.Invite, err error) *MockService_MyInvites_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockService_MyInvites_Call) RunAndReturn(run func(ctx context.Context, actorID string) ([]party.Invite, error)) *MockService_MyInvites_Call {
	_c.Call.Return(run)
	return _c
}

// MyParties provides a mock function for the type MockService
func (_mock *MockService) MyParties(ctx context.Context, actorID string) ([]entity.Party, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for MyParties")
	}

	var r0 []entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Party, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Party); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Party)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_MyParties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyParties'
type MockService_MyParties_Call struct {
	*mock.Call
}

// MyParties is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
func (_e *MockService_Expecter) MyParties(ctx any, actorID any) *MockService_MyParties_Call {
	return &MockService_MyParties_Call{Call: _e.mock.On("MyParties", ctx, actorID)}
}

func (_c *MockService_MyParties_Call) Run(run func(ctx context.Context, actorID string)) *MockService_MyParties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MyParties_Call) Return(partys []entity.Party, err error) *MockService_MyParties_Call {
	_c.Call.Return(partys, err)
	return _c
}

func (_c *MockService_MyParties_Call) RunAndReturn(run func(ctx context.Context, actorID string) ([]entity.Party, error)) *MockService_MyParties_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type MockService
func (_mock *MockService) RemoveMember(ctx context.Context, actorID string, partyID string, targetUserID string) error {
	ret := _mock.Called(ctx, actorID, partyID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - targetUserID string
func (_e *MockService_Expecter) RemoveMember(ctx any, actorID any, partyID any, targetUserID any) *MockService_RemoveMember_Call {
	return &MockService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, actorID, partyID, targetUserID)}
}

func (_c *MockService_RemoveMember_Call) Run(run func(ctx context.Context, actorID string, partyID string, targetUserID string)) *MockService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RemoveMember_Call) Return(err error) *MockService_RemoveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, targetUserID string) error) *MockService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}
