// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_trip

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, trip entity.Trip) (entity.Trip, error) {
	ret := _mock.Called(ctx, trip)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Trip
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Trip) (entity.Trip, error)); ok {
		return returnFunc(ctx, trip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Trip) entity.Trip); ok {
		r0 = returnFunc(ctx, trip)
	} else {
		r0 = ret.Get(0).(entity.Trip)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Trip) error); ok {
		r1 = returnFunc(ctx, trip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trip entity.Trip
func (_e *MockRepository_Expecter) Create(ctx any, trip any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, trip)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, trip entity.Trip)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Trip
		if args[1] != nil {
			arg1 = args[1].(entity.Trip)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(trip1 entity.Trip, err error) *MockRepository_Create_Call {
	_c.Call.Return(trip1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, trip entity.Trip) (entity.Trip, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByPartyIDAndUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindLatestByPartyIDAndUserID(ctx context.Context, partyID string, userID string) (entity.Trip, error) {
	ret := _mock.Called(ctx, partyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByPartyIDAndUserID")
	}

	var r0 entity.Trip
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.Trip, error)); ok {
		return returnFunc(ctx, partyID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.Trip); ok {
		r0 = returnFunc(ctx, partyID, userID)
	} else {
		r0 = ret.Get(0).(entity.Trip)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, partyID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindLatestByPartyIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByPartyIDAndUserID'
type MockRepository_FindLatestByPartyIDAndUserID_Call struct {
	*mock.Call
}

// FindLatestByPartyIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - userID string
func (_e *MockRepository_Expecter) FindLatestByPartyIDAndUserID(ctx any, partyID any, userID any) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	return &MockRepository_FindLatestByPartyIDAndUserID_Call{Call: _e.mock.On("FindLatestByPartyIDAndUserID", ctx, partyID, userID)}
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) Run(run func(ctx context.Context, partyID string, userID string)) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) Return(trip entity.Trip, err error) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Return(trip, err)
	return _c
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, partyID string, userID string) (entity.Trip, error)) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}
