// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_review

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type MockService
func (_mock *MockService) CreateReview(ctx context.Context, actorID string, partyID string, targetUserID string, score int, comment string) (entity.Review, error) {
	ret := _mock.Called(ctx, actorID, partyID, targetUserID, score, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int, string) (entity.Review, error)); ok {
		return returnFunc(ctx, actorID, partyID, targetUserID, score, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int, string) entity.Review); ok {
		r0 = returnFunc(ctx, actorID, partyID, targetUserID, score, comment)
	} else {
		r0 = ret.Get(0).(entity.Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, targetUserID, score, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockService_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - targetUserID string
//   - score int
//   - comment string
func (_e *MockService_Expecter) CreateReview(ctx any, actorID any, partyID any, targetUserID any, score any, comment any) *MockService_CreateReview_Call {
	return &MockService_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, actorID, partyID, targetUserID, score, comment)}
}

func (_c *MockService_CreateReview_Call) Run(run func(ctx context.Context, actorID string, partyID string, targetUserID string, score int, comment string)) *MockService_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_CreateReview_Call) Return(review entity.Review, err error) *MockService_CreateReview_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockService_CreateReview_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, targetUserID string, score int, comment string) (entity.Review, error)) *MockService_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// ListMyReviews provides a mock function for the type MockService
func (_mock *MockService) ListMyReviews(ctx context.Context, actorID string, partyID string) ([]entity.Review, error) {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for ListMyReviews")
	}

	var r0 []entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Review, error)); ok {
		return returnFunc(ctx, actorID, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.Review); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListMyReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMyReviews'
type MockService_ListMyReviews_Call struct {
	*mock.Call
}

// ListMyReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) ListMyReviews(ctx any, actorID any, partyID any) *MockService_ListMyReviews_Call {
	return &MockService_ListMyReviews_Call{Call: _e.mock.On("ListMyReviews", ctx, actorID, partyID)}
}

func (_c *MockService_ListMyReviews_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_ListMyReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListMyReviews_Call) Return(reviews []entity.Review, err error) *MockService_ListMyReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockService_ListMyReviews_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) ([]entity.Review, error)) *MockService_ListMyReviews_Call {
	_c.Call.Return(run)
	return _c
}
