// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_trip

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetMemberPosition provides a mock function for the type MockService
func (_mock *MockService) GetMemberPosition(ctx context.Context, actorID string, partyID string, targetUserID string) (entity.Position, error) {
	ret := _mock.Called(ctx, actorID, partyID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberPosition")
	}

	var r0 entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (entity.Position, error)); ok {
		return returnFunc(ctx, actorID, partyID, targetUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) entity.Position); ok {
		r0 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r0 = ret.Get(0).(entity.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMemberPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberPosition'
type MockService_GetMemberPosition_Call struct {
	*mock.Call
}

// GetMemberPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - targetUserID string
func (_e *MockService_Expecter) GetMemberPosition(ctx any, actorID any, partyID any, targetUserID any) *MockService_GetMemberPosition_Call {
	return &MockService_GetMemberPosition_Call{Call: _e.mock.On("GetMemberPosition", ctx, actorID, partyID, targetUserID)}
}

func (_c *MockService_GetMemberPosition_Call) Run(run func(ctx context.Context, actorID string, partyID string, targetUserID string)) *MockService_GetMemberPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetMemberPosition_Call) Return(position entity.Position, err error) *MockService_GetMemberPosition_Call {
	_c.Call.Return(position, err)
	return _c
}

func (_c *MockService_GetMemberPosition_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, targetUserID string) (entity.Position, error)) *MockService_GetMemberPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetPartyPositions provides a mock function for the type MockService
func (_mock *MockService) GetPartyPositions(ctx context.Context, actorID string, partyID string) ([]entity.Position, error) {
	ret := _mock.Called(ctx, actorID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyPositions")
	}

	var r0 []entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Position, error)); ok {
		return returnFunc(ctx, actorID, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.Position); ok {
		r0 = returnFunc(ctx, actorID, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetPartyPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPartyPositions'
type MockService_GetPartyPositions_Call struct {
	*mock.Call
}

// GetPartyPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
func (_e *MockService_Expecter) GetPartyPositions(ctx any, actorID any, partyID any) *MockService_GetPartyPositions_Call {
	return &MockService_GetPartyPositions_Call{Call: _e.mock.On("GetPartyPositions", ctx, actorID, partyID)}
}

func (_c *MockService_GetPartyPositions_Call) Run(run func(ctx context.Context, actorID string, partyID string)) *MockService_GetPartyPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetPartyPositions_Call) Return(positions []entity.Position, err error) *MockService_GetPartyPositions_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockService_GetPartyPositions_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string) ([]entity.Position, error)) *MockService_GetPartyPositions_Call {
	_c.Call.Return(run)
	return _c
}

// StartTrip provides a mock function for the type MockService
func (_mock *MockService) StartTrip(ctx context.Context, actorID string, partyID string, direction entity.TripDirection, lat float64, lng float64) (entity.Trip, entity.Position, error) {
	ret := _mock.Called(ctx, actorID, partyID, direction, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for StartTrip")
	}

	var r0 entity.Trip
	var r1 entity.Position
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.TripDirection, float64, float64) (entity.Trip, entity.Position, error)); ok {
		return returnFunc(ctx, actorID, partyID, direction, lat, lng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.TripDirection, float64, float64) entity.Trip); ok {
		r0 = returnFunc(ctx, actorID, partyID, direction, lat, lng)
	} else {
		r0 = ret.Get(0).(entity.Trip)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, entity.TripDirection, float64, float64) entity.Position); ok {
		r1 = returnFunc(ctx, actorID, partyID, direction, lat, lng)
	} else {
		r1 = ret.Get(1).(entity.Position)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, entity.TripDirection, float64, float64) error); ok {
		r2 = returnFunc(ctx, actorID, partyID, direction, lat, lng)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_StartTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTrip'
type MockService_StartTrip_Call struct {
	*mock.Call
}

// StartTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - direction entity.TripDirection
//   - lat float64
//   - lng float64
func (_e *MockService_Expecter) StartTrip(ctx any, actorID any, partyID any, direction any, lat any, lng any) *MockService_StartTrip_Call {
	return &MockService_StartTrip_Call{Call: _e.mock.On("StartTrip", ctx, actorID, partyID, direction, lat, lng)}
}

func (_c *MockService_StartTrip_Call) Run(run func(ctx context.Context, actorID string, partyID string, direction entity.TripDirection, lat float64, lng float64)) *MockService_StartTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 entity.TripDirection
		if args[3] != nil {
			arg3 = args[3].(entity.TripDirection)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 float64
		if args[5] != nil {
			arg5 = args[5].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_StartTrip_Call) Return(trip entity.Trip, position entity.Position, err error) *MockService_StartTrip_Call {
	_c.Call.Return(trip, position, err)
	return _c
}

func (_c *MockService_StartTrip_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, direction entity.TripDirection, lat float64, lng float64) (entity.Trip, entity.Position, error)) *MockService_StartTrip_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosition provides a mock function for the type MockService
func (_mock *MockService) UpdatePosition(ctx context.Context, actorID string, partyID string, lat float64, lng float64) (entity.Position, error) {
	ret := _mock.Called(ctx, actorID, partyID, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, float64) (entity.Position, error)); ok {
		return returnFunc(ctx, actorID, partyID, lat, lng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, float64) entity.Position); ok {
		r0 = returnFunc(ctx, actorID, partyID, lat, lng)
	} else {
		r0 = ret.Get(0).(entity.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, float64, float64) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, lat, lng)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdatePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosition'
type MockService_UpdatePosition_Call struct {
	*mock.Call
}

// UpdatePosition is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - lat float64
//   - lng float64
func (_e *MockService_Expecter) UpdatePosition(ctx any, actorID any, partyID any, lat any, lng any) *MockService_UpdatePosition_Call {
	return &MockService_UpdatePosition_Call{Call: _e.mock.On("UpdatePosition", ctx, actorID, partyID, lat, lng)}
}

func (_c *MockService_UpdatePosition_Call) Run(run func(ctx context.Context, actorID string, partyID string, lat float64, lng float64)) *MockService_UpdatePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_UpdatePosition_Call) Return(position entity.Position, err error) *MockService_UpdatePosition_Call {
	_c.Call.Return(position, err)
	return _c
}

func (_c *MockService_UpdatePosition_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, lat float64, lng float64) (entity.Position, error)) *MockService_UpdatePosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTripStatus provides a mock function for the type MockService
func (_mock *MockService) UpdateTripStatus(ctx context.Context, actorID string, partyID string, status entity.TripStatus) (entity.PartyMember, error) {
	ret := _mock.Called(ctx, actorID, partyID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTripStatus")
	}

	var r0 entity.PartyMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.TripStatus) (entity.PartyMember, error)); ok {
		return returnFunc(ctx, actorID, partyID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.TripStatus) entity.PartyMember); ok {
		r0 = returnFunc(ctx, actorID, partyID, status)
	} else {
		r0 = ret.Get(0).(entity.PartyMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, entity.TripStatus) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateTripStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTripStatus'
type MockService_UpdateTripStatus_Call struct {
	*mock.Call
}

// UpdateTripStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - status entity.TripStatus
func (_e *MockService_Expecter) UpdateTripStatus(ctx any, actorID any, partyID any, status any) *MockService_UpdateTripStatus_Call {
	return &MockService_UpdateTripStatus_Call{Call: _e.mock.On("UpdateTripStatus", ctx, actorID, partyID, status)}
}

func (_c *MockService_UpdateTripStatus_Call) Run(run func(ctx context.Context, actorID string, partyID string, status entity.TripStatus)) *MockService_UpdateTripStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 entity.TripStatus
		if args[3] != nil {
			arg3 = args[3].(entity.TripStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateTripStatus_Call) Return(partyMember entity.PartyMember, err error) *MockService_UpdateTripStatus_Call {
	_c.Call.Return(partyMember, err)
	return _c
}

func (_c *MockService_UpdateTripStatus_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, status entity.TripStatus) (entity.PartyMember, error)) *MockService_UpdateTripStatus_Call {
	_c.Call.Return(run)
	return _c
}
