// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_auth

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// InstagramAuthCodeURL provides a mock function for the type MockService
func (_mock *MockService) InstagramAuthCodeURL(state string) string {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for InstagramAuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_InstagramAuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstagramAuthCodeURL'
type MockService_InstagramAuthCodeURL_Call struct {
	*mock.Call
}

// InstagramAuthCodeURL is a helper method to define mock.On call
//   - state string
func (_e *MockService_Expecter) InstagramAuthCodeURL(state any) *MockService_InstagramAuthCodeURL_Call {
	return &MockService_InstagramAuthCodeURL_Call{Call: _e.mock.On("InstagramAuthCodeURL", state)}
}

func (_c *MockService_InstagramAuthCodeURL_Call) Run(run func(state string)) *MockService_InstagramAuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_InstagramAuthCodeURL_Call) Return(s string) *MockService_InstagramAuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_InstagramAuthCodeURL_Call) RunAndReturn(run func(state string) string) *MockService_InstagramAuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithInstagram provides a mock function for the type MockService
func (_mock *MockService) LoginWithInstagram(ctx context.Context, code string) (entity.User, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithInstagram")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_LoginWithInstagram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithInstagram'
type MockService_LoginWithInstagram_Call struct {
	*mock.Call
}

// LoginWithInstagram is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockService_Expecter) LoginWithInstagram(ctx any, code any) *MockService_LoginWithInstagram_Call {
	return &MockService_LoginWithInstagram_Call{Call: _e.mock.On("LoginWithInstagram", ctx, code)}
}

func (_c *MockService_LoginWithInstagram_Call) Run(run func(ctx context.Context, code string)) *MockService_LoginWithInstagram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LoginWithInstagram_Call) Return(user entity.User, err error) *MockService_LoginWithInstagram_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_LoginWithInstagram_Call) RunAndReturn(run func(ctx context.Context, code string) (entity.User, error)) *MockService_LoginWithInstagram_Call {
	_c.Call.Return(run)
	return _c
}
