// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_devicetoken

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockHandler
func (_mock *MockHandler) Register(ctx context.Context, req *dto.RegisterDeviceTokenRequest) (*dto.RegisterDeviceTokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.RegisterDeviceTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterDeviceTokenRequest) (*dto.RegisterDeviceTokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterDeviceTokenRequest) *dto.RegisterDeviceTokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RegisterDeviceTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RegisterDeviceTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RegisterDeviceTokenRequest
func (_e *MockHandler_Expecter) Register(ctx any, req any) *MockHandler_Register_Call {
	return &MockHandler_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockHandler_Register_Call) Run(run func(ctx context.Context, req *dto.RegisterDeviceTokenRequest)) *MockHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RegisterDeviceTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.RegisterDeviceTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Register_Call) Return(registerDeviceTokenResponse *dto.RegisterDeviceTokenResponse, err error) *MockHandler_Register_Call {
	_c.Call.Return(registerDeviceTokenResponse, err)
	return _c
}

func (_c *MockHandler_Register_Call) RunAndReturn(run func(ctx context.Context, req *dto.RegisterDeviceTokenRequest) (*dto.RegisterDeviceTokenResponse, error)) *MockHandler_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type MockHandler
func (_mock *MockHandler) Unregister(ctx context.Context, req *dto.DeleteDeviceTokenRequest) (*dto.DeleteDeviceTokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 *dto.DeleteDeviceTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteDeviceTokenRequest) (*dto.DeleteDeviceTokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteDeviceTokenRequest) *dto.DeleteDeviceTokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteDeviceTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.DeleteDeviceTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockHandler_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.DeleteDeviceTokenRequest
func (_e *MockHandler_Expecter) Unregister(ctx any, req any) *MockHandler_Unregister_Call {
	return &MockHandler_Unregister_Call{Call: _e.mock.On("Unregister", ctx, req)}
}

func (_c *MockHandler_Unregister_Call) Run(run func(ctx context.Context, req *dto.DeleteDeviceTokenRequest)) *MockHandler_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.DeleteDeviceTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.DeleteDeviceTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Unregister_Call) Return(deleteDeviceTokenResponse *dto.DeleteDeviceTokenResponse, err error) *MockHandler_Unregister_Call {
	_c.Call.Return(deleteDeviceTokenResponse, err)
	return _c
}

func (_c *MockHandler_Unregister_Call) RunAndReturn(run func(ctx context.Context, req *dto.DeleteDeviceTokenRequest) (*dto.DeleteDeviceTokenResponse, error)) *MockHandler_Unregister_Call {
	_c.Call.Return(run)
	return _c
}
