// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_party

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, party entity.Party) (entity.Party, error) {
	ret := _mock.Called(ctx, party)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Party) (entity.Party, error)); ok {
		return returnFunc(ctx, party)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Party) entity.Party); ok {
		r0 = returnFunc(ctx, party)
	} else {
		r0 = ret.Get(0).(entity.Party)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Party) error); ok {
		r1 = returnFunc(ctx, party)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - party entity.Party
func (_e *MockRepository_Expecter) Create(ctx any, party any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, party)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, party entity.Party)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Party
		if args[1] != nil {
			arg1 = args[1].(entity.Party)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(party1 entity.Party, err error) *MockRepository_Create_Call {
	_c.Call.Return(party1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, party entity.Party) (entity.Party, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (entity.Party, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Party, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Party); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Party)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(party entity.Party, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(party, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.Party, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByIDs(ctx context.Context, ids []string) ([]entity.Party, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []entity.Party
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]entity.Party, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []entity.Party); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Party)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) FindByIDs(ctx any, ids any) *MockRepository_FindByIDs_Call {
	return &MockRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByIDs_Call) Return(partys []entity.Party, err error) *MockRepository_FindByIDs_Call {
	_c.Call.Return(partys, err)
	return _c
}

func (_c *MockRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]entity.Party, error)) *MockRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}
