// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_instagramoauth

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Callback provides a mock function for the type MockHandler
func (_mock *MockHandler) Callback(ctx context.Context, req *dto.InstagramCallbackRequest) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Callback")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InstagramCallbackRequest) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InstagramCallbackRequest) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.InstagramCallbackRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type MockHandler_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.InstagramCallbackRequest
func (_e *MockHandler_Expecter) Callback(ctx any, req any) *MockHandler_Callback_Call {
	return &MockHandler_Callback_Call{Call: _e.mock.On("Callback", ctx, req)}
}

func (_c *MockHandler_Callback_Call) Run(run func(ctx context.Context, req *dto.InstagramCallbackRequest)) *MockHandler_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.InstagramCallbackRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.InstagramCallbackRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Callback_Call) Return(userResponse *dto.UserResponse, err error) *MockHandler_Callback_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockHandler_Callback_Call) RunAndReturn(run func(ctx context.Context, req *dto.InstagramCallbackRequest) (*dto.UserResponse, error)) *MockHandler_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockHandler
func (_mock *MockHandler) Start(ctx context.Context, req *dto.InstagramStartRequest) (*dto.RedirectResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *dto.RedirectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InstagramStartRequest) (*dto.RedirectResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InstagramStartRequest) *dto.RedirectResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RedirectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.InstagramStartRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHandler_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.InstagramStartRequest
func (_e *MockHandler_Expecter) Start(ctx any, req any) *MockHandler_Start_Call {
	return &MockHandler_Start_Call{Call: _e.mock.On("Start", ctx, req)}
}

func (_c *MockHandler_Start_Call) Run(run func(ctx context.Context, req *dto.InstagramStartRequest)) *MockHandler_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.InstagramStartRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.InstagramStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Start_Call) Return(redirectResponse *dto.RedirectResponse, err error) *MockHandler_Start_Call {
	_c.Call.Return(redirectResponse, err)
	return _c
}

func (_c *MockHandler_Start_Call) RunAndReturn(run func(ctx context.Context, req *dto.InstagramStartRequest) (*dto.RedirectResponse, error)) *MockHandler_Start_Call {
	_c.Call.Return(run)
	return _c
}
