// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_trip

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// GetMemberPosition provides a mock function for the type MockHandler
func (_mock *MockHandler) GetMemberPosition(ctx context.Context, req *dto.GetMemberPositionRequest) (*dto.PositionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberPosition")
	}

	var r0 *dto.PositionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetMemberPositionRequest) (*dto.PositionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetMemberPositionRequest) *dto.PositionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PositionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.GetMemberPositionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_GetMemberPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberPosition'
type MockHandler_GetMemberPosition_Call struct {
	*mock.Call
}

// GetMemberPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.GetMemberPositionRequest
func (_e *MockHandler_Expecter) GetMemberPosition(ctx any, req any) *MockHandler_GetMemberPosition_Call {
	return &MockHandler_GetMemberPosition_Call{Call: _e.mock.On("GetMemberPosition", ctx, req)}
}

func (_c *MockHandler_GetMemberPosition_Call) Run(run func(ctx context.Context, req *dto.GetMemberPositionRequest)) *MockHandler_GetMemberPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.GetMemberPositionRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.GetMemberPositionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetMemberPosition_Call) Return(positionResponse *dto.PositionResponse, err error) *MockHandler_GetMemberPosition_Call {
	_c.Call.Return(positionResponse, err)
	return _c
}

func (_c *MockHandler_GetMemberPosition_Call) RunAndReturn(run func(ctx context.Context, req *dto.GetMemberPositionRequest) (*dto.PositionResponse, error)) *MockHandler_GetMemberPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetPartyPositions provides a mock function for the type MockHandler
func (_mock *MockHandler) GetPartyPositions(ctx context.Context, req *dto.GetPartyPositionsRequest) (*dto.PositionsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyPositions")
	}

	var r0 *dto.PositionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetPartyPositionsRequest) (*dto.PositionsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetPartyPositionsRequest) *dto.PositionsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PositionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.GetPartyPositionsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_GetPartyPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPartyPositions'
type MockHandler_GetPartyPositions_Call struct {
	*mock.Call
}

// GetPartyPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.GetPartyPositionsRequest
func (_e *MockHandler_Expecter) GetPartyPositions(ctx any, req any) *MockHandler_GetPartyPositions_Call {
	return &MockHandler_GetPartyPositions_Call{Call: _e.mock.On("GetPartyPositions", ctx, req)}
}

func (_c *MockHandler_GetPartyPositions_Call) Run(run func(ctx context.Context, req *dto.GetPartyPositionsRequest)) *MockHandler_GetPartyPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.GetPartyPositionsRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.GetPartyPositionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetPartyPositions_Call) Return(positionsResponse *dto.PositionsResponse, err error) *MockHandler_GetPartyPositions_Call {
	_c.Call.Return(positionsResponse, err)
	return _c
}

func (_c *MockHandler_GetPartyPositions_Call) RunAndReturn(run func(ctx context.Context, req *dto.GetPartyPositionsRequest) (*dto.PositionsResponse, error)) *MockHandler_GetPartyPositions_Call {
	_c.Call.Return(run)
	return _c
}

// StartTrip provides a mock function for the type MockHandler
func (_mock *MockHandler) StartTrip(ctx context.Context, req *dto.StartTripRequest) (*dto.StartTripResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartTrip")
	}

	var r0 *dto.StartTripResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.StartTripRequest) (*dto.StartTripResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.StartTripRequest) *dto.StartTripResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StartTripResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.StartTripRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_StartTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTrip'
type MockHandler_StartTrip_Call struct {
	*mock.Call
}

// StartTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.StartTripRequest
func (_e *MockHandler_Expecter) StartTrip(ctx any, req any) *MockHandler_StartTrip_Call {
	return &MockHandler_StartTrip_Call{Call: _e.mock.On("StartTrip", ctx, req)}
}

func (_c *MockHandler_StartTrip_Call) Run(run func(ctx context.Context, req *dto.StartTripRequest)) *MockHandler_StartTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.StartTripRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.StartTripRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_StartTrip_Call) Return(startTripResponse *dto.StartTripResponse, err error) *MockHandler_StartTrip_Call {
	_c.Call.Return(startTripResponse, err)
	return _c
}

func (_c *MockHandler_StartTrip_Call) RunAndReturn(run func(ctx context.Context, req *dto.StartTripRequest) (*dto.StartTripResponse, error)) *MockHandler_StartTrip_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosition provides a mock function for the type MockHandler
func (_mock *MockHandler) UpdatePosition(ctx context.Context, req *dto.UpdatePositionRequest) (*dto.PositionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 *dto.PositionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdatePositionRequest) (*dto.PositionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdatePositionRequest) *dto.PositionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PositionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UpdatePositionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_UpdatePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosition'
type MockHandler_UpdatePosition_Call struct {
	*mock.Call
}

// UpdatePosition is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.UpdatePositionRequest
func (_e *MockHandler_Expecter) UpdatePosition(ctx any, req any) *MockHandler_UpdatePosition_Call {
	return &MockHandler_UpdatePosition_Call{Call: _e.mock.On("UpdatePosition", ctx, req)}
}

func (_c *MockHandler_UpdatePosition_Call) Run(run func(ctx context.Context, req *dto.UpdatePositionRequest)) *MockHandler_UpdatePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UpdatePositionRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UpdatePositionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_UpdatePosition_Call) Return(positionResponse *dto.PositionResponse, err error) *MockHandler_UpdatePosition_Call {
	_c.Call.Return(positionResponse, err)
	return _c
}

func (_c *MockHandler_UpdatePosition_Call) RunAndReturn(run func(ctx context.Context, req *dto.UpdatePositionRequest) (*dto.PositionResponse, error)) *MockHandler_UpdatePosition_Call {
	_c.Call.Return(run)
	return _c
}
