// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_review

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, review entity.Review) (entity.Review, error) {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Review) (entity.Review, error)); ok {
		return returnFunc(ctx, review)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Review) entity.Review); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Get(0).(entity.Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Review) error); ok {
		r1 = returnFunc(ctx, review)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - review entity.Review
func (_e *MockRepository_Expecter) Create(ctx any, review any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, review)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, review entity.Review)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Review
		if args[1] != nil {
			arg1 = args[1].(entity.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(review1 entity.Review, err error) *MockRepository_Create_Call {
	_c.Call.Return(review1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, review entity.Review) (entity.Review, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPartyIDAndReviewerID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByPartyIDAndReviewerID(ctx context.Context, partyID string, reviewerID string) ([]entity.Review, error) {
	ret := _mock.Called(ctx, partyID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPartyIDAndReviewerID")
	}

	var r0 []entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Review, error)); ok {
		return returnFunc(ctx, partyID, reviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []entity.Review); ok {
		r0 = returnFunc(ctx, partyID, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, partyID, reviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByPartyIDAndReviewerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPartyIDAndReviewerID'
type MockRepository_FindByPartyIDAndReviewerID_Call struct {
	*mock.Call
}

// FindByPartyIDAndReviewerID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - reviewerID string
func (_e *MockRepository_Expecter) FindByPartyIDAndReviewerID(ctx any, partyID any, reviewerID any) *MockRepository_FindByPartyIDAndReviewerID_Call {
	return &MockRepository_FindByPartyIDAndReviewerID_Call{Call: _e.mock.On("FindByPartyIDAndReviewerID", ctx, partyID, reviewerID)}
}

func (_c *MockRepository_FindByPartyIDAndReviewerID_Call) Run(run func(ctx context.Context, partyID string, reviewerID string)) *MockRepository_FindByPartyIDAndReviewerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindByPartyIDAndReviewerID_Call) Return(reviews []entity.Review, err error) *MockRepository_FindByPartyIDAndReviewerID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockRepository_FindByPartyIDAndReviewerID_Call) RunAndReturn(run func(ctx context.Context, partyID string, reviewerID string) ([]entity.Review, error)) *MockRepository_FindByPartyIDAndReviewerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPartyIDReviewerIDAndTargetUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByPartyIDReviewerIDAndTargetUserID(ctx context.Context, partyID string, reviewerID string, targetUserID string) (entity.Review, error) {
	ret := _mock.Called(ctx, partyID, reviewerID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPartyIDReviewerIDAndTargetUserID")
	}

	var r0 entity.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (entity.Review, error)); ok {
		return returnFunc(ctx, partyID, reviewerID, targetUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) entity.Review); ok {
		r0 = returnFunc(ctx, partyID, reviewerID, targetUserID)
	} else {
		r0 = ret.Get(0).(entity.Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, partyID, reviewerID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPartyIDReviewerIDAndTargetUserID'
type MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call struct {
	*mock.Call
}

// FindByPartyIDReviewerIDAndTargetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - reviewerID string
//   - targetUserID string
func (_e *MockRepository_Expecter) FindByPartyIDReviewerIDAndTargetUserID(ctx any, partyID any, reviewerID any, targetUserID any) *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call {
	return &MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call{Call: _e.mock.On("FindByPartyIDReviewerIDAndTargetUserID", ctx, partyID, reviewerID, targetUserID)}
}

func (_c *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call) Run(run func(ctx context.Context, partyID string, reviewerID string, targetUserID string)) *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call) Return(review entity.Review, err error) *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call) RunAndReturn(run func(ctx context.Context, partyID string, reviewerID string, targetUserID string) (entity.Review, error)) *MockRepository_FindByPartyIDReviewerIDAndTargetUserID_Call {
	_c.Call.Return(run)
	return _c
}
