// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_user

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, user entity.User) (entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *MockRepository_Expecter) Create(ctx any, user any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, user entity.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.User
		if args[1] != nil {
			arg1 = args[1].(entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(user1 entity.User, err error) *MockRepository_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user entity.User) (entity.User, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGoogleUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByGoogleUserID(ctx context.Context, googleUserID string) (entity.User, error) {
	ret := _mock.Called(ctx, googleUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGoogleUserID")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, googleUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, googleUserID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, googleUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByGoogleUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGoogleUserID'
type MockRepository_FindByGoogleUserID_Call struct {
	*mock.Call
}

// FindByGoogleUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - googleUserID string
func (_e *MockRepository_Expecter) FindByGoogleUserID(ctx any, googleUserID any) *MockRepository_FindByGoogleUserID_Call {
	return &MockRepository_FindByGoogleUserID_Call{Call: _e.mock.On("FindByGoogleUserID", ctx, googleUserID)}
}

func (_c *MockRepository_FindByGoogleUserID_Call) Run(run func(ctx context.Context, googleUserID string)) *MockRepository_FindByGoogleUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByGoogleUserID_Call) Return(user entity.User, err error) *MockRepository_FindByGoogleUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByGoogleUserID_Call) RunAndReturn(run func(ctx context.Context, googleUserID string) (entity.User, error)) *MockRepository_FindByGoogleUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(user entity.User, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.User, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByUsername(ctx context.Context, username string) (entity.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockRepository_Expecter) FindByUsername(ctx any, username any) *MockRepository_FindByUsername_Call {
	return &MockRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByUsername_Call) Return(user entity.User, err error) *MockRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (entity.User, error)) *MockRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementLateCount provides a mock function for the type MockRepository
func (_mock *MockRepository) IncrementLateCount(ctx context.Context, id string) (entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementLateCount")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IncrementLateCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementLateCount'
type MockRepository_IncrementLateCount_Call struct {
	*mock.Call
}

// IncrementLateCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) IncrementLateCount(ctx any, id any) *MockRepository_IncrementLateCount_Call {
	return &MockRepository_IncrementLateCount_Call{Call: _e.mock.On("IncrementLateCount", ctx, id)}
}

func (_c *MockRepository_IncrementLateCount_Call) Run(run func(ctx context.Context, id string)) *MockRepository_IncrementLateCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IncrementLateCount_Call) Return(user entity.User, err error) *MockRepository_IncrementLateCount_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_IncrementLateCount_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.User, error)) *MockRepository_IncrementLateCount_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementOnTimeCount provides a mock function for the type MockRepository
func (_mock *MockRepository) IncrementOnTimeCount(ctx context.Context, id string) (entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementOnTimeCount")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IncrementOnTimeCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementOnTimeCount'
type MockRepository_IncrementOnTimeCount_Call struct {
	*mock.Call
}

// IncrementOnTimeCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) IncrementOnTimeCount(ctx any, id any) *MockRepository_IncrementOnTimeCount_Call {
	return &MockRepository_IncrementOnTimeCount_Call{Call: _e.mock.On("IncrementOnTimeCount", ctx, id)}
}

func (_c *MockRepository_IncrementOnTimeCount_Call) Run(run func(ctx context.Context, id string)) *MockRepository_IncrementOnTimeCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IncrementOnTimeCount_Call) Return(user entity.User, err error) *MockRepository_IncrementOnTimeCount_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_IncrementOnTimeCount_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.User, error)) *MockRepository_IncrementOnTimeCount_Call {
	_c.Call.Return(run)
	return _c
}

// RecordRating provides a mock function for the type MockRepository
func (_mock *MockRepository) RecordRating(ctx context.Context, id string, score int) (entity.User, error) {
	ret := _mock.Called(ctx, id, score)

	if len(ret) == 0 {
		panic("no return value specified for RecordRating")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (entity.User, error)); ok {
		return returnFunc(ctx, id, score)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) entity.User); ok {
		r0 = returnFunc(ctx, id, score)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, id, score)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RecordRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRating'
type MockRepository_RecordRating_Call struct {
	*mock.Call
}

// RecordRating is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - score int
func (_e *MockRepository_Expecter) RecordRating(ctx any, id any, score any) *MockRepository_RecordRating_Call {
	return &MockRepository_RecordRating_Call{Call: _e.mock.On("RecordRating", ctx, id, score)}
}

func (_c *MockRepository_RecordRating_Call) Run(run func(ctx context.Context, id string, score int)) *MockRepository_RecordRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RecordRating_Call) Return(user entity.User, err error) *MockRepository_RecordRating_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_RecordRating_Call) RunAndReturn(run func(ctx context.Context, id string, score int) (entity.User, error)) *MockRepository_RecordRating_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockRepository
func (_mock *MockRepository) Search(ctx context.Context, query string) ([]entity.User, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.User, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.User); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockRepository_Expecter) Search(ctx any, query any) *MockRepository_Search_Call {
	return &MockRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockRepository_Search_Call) Run(run func(ctx context.Context, query string)) *MockRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Search_Call) Return(users []entity.User, err error) *MockRepository_Search_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]entity.User, error)) *MockRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateProfile(ctx context.Context, id string, displayName string, username string, emergencyContactName string, emergencyContactPhone string) (entity.User, error) {
	ret := _mock.Called(ctx, id, displayName, username, emergencyContactName, emergencyContactPhone)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (entity.User, error)); ok {
		return returnFunc(ctx, id, displayName, username, emergencyContactName, emergencyContactPhone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) entity.User); ok {
		r0 = returnFunc(ctx, id, displayName, username, emergencyContactName, emergencyContactPhone)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, displayName, username, emergencyContactName, emergencyContactPhone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - displayName string
//   - username string
//   - emergencyContactName string
//   - emergencyContactPhone string
func (_e *MockRepository_Expecter) UpdateProfile(ctx any, id any, displayName any, username any, emergencyContactName any, emergencyContactPhone any) *MockRepository_UpdateProfile_Call {
	return &MockRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, id, displayName, username, emergencyContactName, emergencyContactPhone)}
}

func (_c *MockRepository_UpdateProfile_Call) Run(run func(ctx context.Context, id string, displayName string, username string, emergencyContactName string, emergencyContactPhone string)) *MockRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateProfile_Call) Return(user entity.User, err error) *MockRepository_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, id string, displayName string, username string, emergencyContactName string, emergencyContactPhone string) (entity.User, error)) *MockRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfileImage provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateProfileImage(ctx context.Context, id string, profileImageURL string) (entity.User, error) {
	ret := _mock.Called(ctx, id, profileImageURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileImage")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.User, error)); ok {
		return returnFunc(ctx, id, profileImageURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.User); ok {
		r0 = returnFunc(ctx, id, profileImageURL)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, profileImageURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateProfileImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfileImage'
type MockRepository_UpdateProfileImage_Call struct {
	*mock.Call
}

// UpdateProfileImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - profileImageURL string
func (_e *MockRepository_Expecter) UpdateProfileImage(ctx any, id any, profileImageURL any) *MockRepository_UpdateProfileImage_Call {
	return &MockRepository_UpdateProfileImage_Call{Call: _e.mock.On("UpdateProfileImage", ctx, id, profileImageURL)}
}

func (_c *MockRepository_UpdateProfileImage_Call) Run(run func(ctx context.Context, id string, profileImageURL string)) *MockRepository_UpdateProfileImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateProfileImage_Call) Return(user entity.User, err error) *MockRepository_UpdateProfileImage_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_UpdateProfileImage_Call) RunAndReturn(run func(ctx context.Context, id string, profileImageURL string) (entity.User, error)) *MockRepository_UpdateProfileImage_Call {
	_c.Call.Return(run)
	return _c
}
