// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_user

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, user entity.User) (entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *MockRepository_Expecter) Create(ctx any, user any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, user entity.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.User
		if args[1] != nil {
			arg1 = args[1].(entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(user1 entity.User, err error) *MockRepository_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user entity.User) (entity.User, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(user entity.User, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.User, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByInstagramUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByInstagramUserID(ctx context.Context, instagramUserID string) (entity.User, error) {
	ret := _mock.Called(ctx, instagramUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByInstagramUserID")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, instagramUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, instagramUserID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, instagramUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByInstagramUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByInstagramUserID'
type MockRepository_FindByInstagramUserID_Call struct {
	*mock.Call
}

// FindByInstagramUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - instagramUserID string
func (_e *MockRepository_Expecter) FindByInstagramUserID(ctx any, instagramUserID any) *MockRepository_FindByInstagramUserID_Call {
	return &MockRepository_FindByInstagramUserID_Call{Call: _e.mock.On("FindByInstagramUserID", ctx, instagramUserID)}
}

func (_c *MockRepository_FindByInstagramUserID_Call) Run(run func(ctx context.Context, instagramUserID string)) *MockRepository_FindByInstagramUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByInstagramUserID_Call) Return(user entity.User, err error) *MockRepository_FindByInstagramUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByInstagramUserID_Call) RunAndReturn(run func(ctx context.Context, instagramUserID string) (entity.User, error)) *MockRepository_FindByInstagramUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockRepository
func (_mock *MockRepository) Search(ctx context.Context, query string) ([]entity.User, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.User, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.User); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockRepository_Expecter) Search(ctx any, query any) *MockRepository_Search_Call {
	return &MockRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockRepository_Search_Call) Run(run func(ctx context.Context, query string)) *MockRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Search_Call) Return(users []entity.User, err error) *MockRepository_Search_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]entity.User, error)) *MockRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}
