// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_review

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type MockHandler
func (_mock *MockHandler) CreateReview(ctx context.Context, req *dto.CreateReviewRequest) (*dto.ReviewResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 *dto.ReviewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateReviewRequest) (*dto.ReviewResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateReviewRequest) *dto.ReviewResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ReviewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateReviewRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockHandler_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateReviewRequest
func (_e *MockHandler_Expecter) CreateReview(ctx any, req any) *MockHandler_CreateReview_Call {
	return &MockHandler_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, req)}
}

func (_c *MockHandler_CreateReview_Call) Run(run func(ctx context.Context, req *dto.CreateReviewRequest)) *MockHandler_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateReviewRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateReviewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_CreateReview_Call) Return(reviewResponse *dto.ReviewResponse, err error) *MockHandler_CreateReview_Call {
	_c.Call.Return(reviewResponse, err)
	return _c
}

func (_c *MockHandler_CreateReview_Call) RunAndReturn(run func(ctx context.Context, req *dto.CreateReviewRequest) (*dto.ReviewResponse, error)) *MockHandler_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// ListMyReviews provides a mock function for the type MockHandler
func (_mock *MockHandler) ListMyReviews(ctx context.Context, req *dto.ListMyReviewsRequest) (*dto.ReviewsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListMyReviews")
	}

	var r0 *dto.ReviewsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListMyReviewsRequest) (*dto.ReviewsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListMyReviewsRequest) *dto.ReviewsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ReviewsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.ListMyReviewsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_ListMyReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMyReviews'
type MockHandler_ListMyReviews_Call struct {
	*mock.Call
}

// ListMyReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListMyReviewsRequest
func (_e *MockHandler_Expecter) ListMyReviews(ctx any, req any) *MockHandler_ListMyReviews_Call {
	return &MockHandler_ListMyReviews_Call{Call: _e.mock.On("ListMyReviews", ctx, req)}
}

func (_c *MockHandler_ListMyReviews_Call) Run(run func(ctx context.Context, req *dto.ListMyReviewsRequest)) *MockHandler_ListMyReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ListMyReviewsRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.ListMyReviewsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_ListMyReviews_Call) Return(reviewsResponse *dto.ReviewsResponse, err error) *MockHandler_ListMyReviews_Call {
	_c.Call.Return(reviewsResponse, err)
	return _c
}

func (_c *MockHandler_ListMyReviews_Call) RunAndReturn(run func(ctx context.Context, req *dto.ListMyReviewsRequest) (*dto.ReviewsResponse, error)) *MockHandler_ListMyReviews_Call {
	_c.Call.Return(run)
	return _c
}
