// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_story

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(ctx context.Context, req *dto.CreateStoryRequest) (*dto.StoryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.StoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateStoryRequest) (*dto.StoryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateStoryRequest) *dto.StoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateStoryRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateStoryRequest
func (_e *MockHandler_Expecter) Create(ctx any, req any) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockHandler_Create_Call) Run(run func(ctx context.Context, req *dto.CreateStoryRequest)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateStoryRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateStoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return(storyResponse *dto.StoryResponse, err error) *MockHandler_Create_Call {
	_c.Call.Return(storyResponse, err)
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(ctx context.Context, req *dto.CreateStoryRequest) (*dto.StoryResponse, error)) *MockHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHandler
func (_mock *MockHandler) Delete(ctx context.Context, req *dto.DeleteStoryRequest) (*dto.DeleteStoryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *dto.DeleteStoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteStoryRequest) (*dto.DeleteStoryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteStoryRequest) *dto.DeleteStoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteStoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.DeleteStoryRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.DeleteStoryRequest
func (_e *MockHandler_Expecter) Delete(ctx any, req any) *MockHandler_Delete_Call {
	return &MockHandler_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockHandler_Delete_Call) Run(run func(ctx context.Context, req *dto.DeleteStoryRequest)) *MockHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.DeleteStoryRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.DeleteStoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Delete_Call) Return(deleteStoryResponse *dto.DeleteStoryResponse, err error) *MockHandler_Delete_Call {
	_c.Call.Return(deleteStoryResponse, err)
	return _c
}

func (_c *MockHandler_Delete_Call) RunAndReturn(run func(ctx context.Context, req *dto.DeleteStoryRequest) (*dto.DeleteStoryResponse, error)) *MockHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockHandler
func (_mock *MockHandler) ListByUser(ctx context.Context, req *dto.ListStoriesByUserRequest) (*dto.StoriesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 *dto.StoriesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListStoriesByUserRequest) (*dto.StoriesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListStoriesByUserRequest) *dto.StoriesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StoriesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.ListStoriesByUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockHandler_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListStoriesByUserRequest
func (_e *MockHandler_Expecter) ListByUser(ctx any, req any) *MockHandler_ListByUser_Call {
	return &MockHandler_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, req)}
}

func (_c *MockHandler_ListByUser_Call) Run(run func(ctx context.Context, req *dto.ListStoriesByUserRequest)) *MockHandler_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ListStoriesByUserRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.ListStoriesByUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_ListByUser_Call) Return(storiesResponse *dto.StoriesResponse, err error) *MockHandler_ListByUser_Call {
	_c.Call.Return(storiesResponse, err)
	return _c
}

func (_c *MockHandler_ListByUser_Call) RunAndReturn(run func(ctx context.Context, req *dto.ListStoriesByUserRequest) (*dto.StoriesResponse, error)) *MockHandler_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
