// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_fcm

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// SendCheckInRequest provides a mock function for the type MockClient
func (_mock *MockClient) SendCheckInRequest(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string) error {
	ret := _mock.Called(ctx, token, meetupID, fromUserID, fromDisplayName)

	if len(ret) == 0 {
		panic("no return value specified for SendCheckInRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, token, meetupID, fromUserID, fromDisplayName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendCheckInRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCheckInRequest'
type MockClient_SendCheckInRequest_Call struct {
	*mock.Call
}

// SendCheckInRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - meetupID string
//   - fromUserID string
//   - fromDisplayName string
func (_e *MockClient_Expecter) SendCheckInRequest(ctx any, token any, meetupID any, fromUserID any, fromDisplayName any) *MockClient_SendCheckInRequest_Call {
	return &MockClient_SendCheckInRequest_Call{Call: _e.mock.On("SendCheckInRequest", ctx, token, meetupID, fromUserID, fromDisplayName)}
}

func (_c *MockClient_SendCheckInRequest_Call) Run(run func(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string)) *MockClient_SendCheckInRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_SendCheckInRequest_Call) Return(err error) *MockClient_SendCheckInRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendCheckInRequest_Call) RunAndReturn(run func(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string) error) *MockClient_SendCheckInRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendNudge provides a mock function for the type MockClient
func (_mock *MockClient) SendNudge(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string) error {
	ret := _mock.Called(ctx, token, meetupID, fromUserID, fromDisplayName)

	if len(ret) == 0 {
		panic("no return value specified for SendNudge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, token, meetupID, fromUserID, fromDisplayName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendNudge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNudge'
type MockClient_SendNudge_Call struct {
	*mock.Call
}

// SendNudge is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - meetupID string
//   - fromUserID string
//   - fromDisplayName string
func (_e *MockClient_Expecter) SendNudge(ctx any, token any, meetupID any, fromUserID any, fromDisplayName any) *MockClient_SendNudge_Call {
	return &MockClient_SendNudge_Call{Call: _e.mock.On("SendNudge", ctx, token, meetupID, fromUserID, fromDisplayName)}
}

func (_c *MockClient_SendNudge_Call) Run(run func(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string)) *MockClient_SendNudge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_SendNudge_Call) Return(err error) *MockClient_SendNudge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendNudge_Call) RunAndReturn(run func(ctx context.Context, token string, meetupID string, fromUserID string, fromDisplayName string) error) *MockClient_SendNudge_Call {
	_c.Call.Return(run)
	return _c
}
