// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_party

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// AcceptInvite provides a mock function for the type MockHandler
func (_mock *MockHandler) AcceptInvite(ctx context.Context, req *dto.AcceptInviteRequest) (*dto.PartyMemberResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvite")
	}

	var r0 *dto.PartyMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AcceptInviteRequest) (*dto.PartyMemberResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AcceptInviteRequest) *dto.PartyMemberResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AcceptInviteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_AcceptInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvite'
type MockHandler_AcceptInvite_Call struct {
	*mock.Call
}

// AcceptInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.AcceptInviteRequest
func (_e *MockHandler_Expecter) AcceptInvite(ctx any, req any) *MockHandler_AcceptInvite_Call {
	return &MockHandler_AcceptInvite_Call{Call: _e.mock.On("AcceptInvite", ctx, req)}
}

func (_c *MockHandler_AcceptInvite_Call) Run(run func(ctx context.Context, req *dto.AcceptInviteRequest)) *MockHandler_AcceptInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AcceptInviteRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.AcceptInviteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_AcceptInvite_Call) Return(partyMemberResponse *dto.PartyMemberResponse, err error) *MockHandler_AcceptInvite_Call {
	_c.Call.Return(partyMemberResponse, err)
	return _c
}

func (_c *MockHandler_AcceptInvite_Call) RunAndReturn(run func(ctx context.Context, req *dto.AcceptInviteRequest) (*dto.PartyMemberResponse, error)) *MockHandler_AcceptInvite_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(ctx context.Context, req *dto.CreatePartyRequest) (*dto.PartyResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.PartyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreatePartyRequest) (*dto.PartyResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreatePartyRequest) *dto.PartyResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreatePartyRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreatePartyRequest
func (_e *MockHandler_Expecter) Create(ctx any, req any) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockHandler_Create_Call) Run(run func(ctx context.Context, req *dto.CreatePartyRequest)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreatePartyRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CreatePartyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return(partyResponse *dto.PartyResponse, err error) *MockHandler_Create_Call {
	_c.Call.Return(partyResponse, err)
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(ctx context.Context, req *dto.CreatePartyRequest) (*dto.PartyResponse, error)) *MockHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineInvite provides a mock function for the type MockHandler
func (_mock *MockHandler) DeclineInvite(ctx context.Context, req *dto.DeclineInviteRequest) (*dto.DeclineInviteResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeclineInvite")
	}

	var r0 *dto.DeclineInviteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeclineInviteRequest) (*dto.DeclineInviteResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeclineInviteRequest) *dto.DeclineInviteResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeclineInviteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.DeclineInviteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_DeclineInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineInvite'
type MockHandler_DeclineInvite_Call struct {
	*mock.Call
}

// DeclineInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.DeclineInviteRequest
func (_e *MockHandler_Expecter) DeclineInvite(ctx any, req any) *MockHandler_DeclineInvite_Call {
	return &MockHandler_DeclineInvite_Call{Call: _e.mock.On("DeclineInvite", ctx, req)}
}

func (_c *MockHandler_DeclineInvite_Call) Run(run func(ctx context.Context, req *dto.DeclineInviteRequest)) *MockHandler_DeclineInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.DeclineInviteRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.DeclineInviteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_DeclineInvite_Call) Return(declineInviteResponse *dto.DeclineInviteResponse, err error) *MockHandler_DeclineInvite_Call {
	_c.Call.Return(declineInviteResponse, err)
	return _c
}

func (_c *MockHandler_DeclineInvite_Call) RunAndReturn(run func(ctx context.Context, req *dto.DeclineInviteRequest) (*dto.DeclineInviteResponse, error)) *MockHandler_DeclineInvite_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockHandler
func (_mock *MockHandler) Get(ctx context.Context, req *dto.GetPartyRequest) (*dto.PartyResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.PartyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetPartyRequest) (*dto.PartyResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetPartyRequest) *dto.PartyResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.GetPartyRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.GetPartyRequest
func (_e *MockHandler_Expecter) Get(ctx any, req any) *MockHandler_Get_Call {
	return &MockHandler_Get_Call{Call: _e.mock.On("Get", ctx, req)}
}

func (_c *MockHandler_Get_Call) Run(run func(ctx context.Context, req *dto.GetPartyRequest)) *MockHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.GetPartyRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.GetPartyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Get_Call) Return(partyResponse *dto.PartyResponse, err error) *MockHandler_Get_Call {
	_c.Call.Return(partyResponse, err)
	return _c
}

func (_c *MockHandler_Get_Call) RunAndReturn(run func(ctx context.Context, req *dto.GetPartyRequest) (*dto.PartyResponse, error)) *MockHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type MockHandler
func (_mock *MockHandler) Invite(ctx context.Context, req *dto.InviteToPartyRequest) (*dto.PartyMemberResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 *dto.PartyMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InviteToPartyRequest) (*dto.PartyMemberResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.InviteToPartyRequest) *dto.PartyMemberResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.InviteToPartyRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockHandler_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.InviteToPartyRequest
func (_e *MockHandler_Expecter) Invite(ctx any, req any) *MockHandler_Invite_Call {
	return &MockHandler_Invite_Call{Call: _e.mock.On("Invite", ctx, req)}
}

func (_c *MockHandler_Invite_Call) Run(run func(ctx context.Context, req *dto.InviteToPartyRequest)) *MockHandler_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.InviteToPartyRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.InviteToPartyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Invite_Call) Return(partyMemberResponse *dto.PartyMemberResponse, err error) *MockHandler_Invite_Call {
	_c.Call.Return(partyMemberResponse, err)
	return _c
}

func (_c *MockHandler_Invite_Call) RunAndReturn(run func(ctx context.Context, req *dto.InviteToPartyRequest) (*dto.PartyMemberResponse, error)) *MockHandler_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type MockHandler
func (_mock *MockHandler) ListMembers(ctx context.Context, req *dto.ListPartyMembersRequest) (*dto.PartyMembersResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 *dto.PartyMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListPartyMembersRequest) (*dto.PartyMembersResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListPartyMembersRequest) *dto.PartyMembersResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.ListPartyMembersRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockHandler_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListPartyMembersRequest
func (_e *MockHandler_Expecter) ListMembers(ctx any, req any) *MockHandler_ListMembers_Call {
	return &MockHandler_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, req)}
}

func (_c *MockHandler_ListMembers_Call) Run(run func(ctx context.Context, req *dto.ListPartyMembersRequest)) *MockHandler_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ListPartyMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.ListPartyMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_ListMembers_Call) Return(partyMembersResponse *dto.PartyMembersResponse, err error) *MockHandler_ListMembers_Call {
	_c.Call.Return(partyMembersResponse, err)
	return _c
}

func (_c *MockHandler_ListMembers_Call) RunAndReturn(run func(ctx context.Context, req *dto.ListPartyMembersRequest) (*dto.PartyMembersResponse, error)) *MockHandler_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// MyInvites provides a mock function for the type MockHandler
func (_mock *MockHandler) MyInvites(ctx context.Context, req *dto.MyInvitesRequest) (*dto.PartyInvitesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MyInvites")
	}

	var r0 *dto.PartyInvitesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.MyInvitesRequest) (*dto.PartyInvitesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.MyInvitesRequest) *dto.PartyInvitesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartyInvitesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.MyInvitesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_MyInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyInvites'
type MockHandler_MyInvites_Call struct {
	*mock.Call
}

// MyInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.MyInvitesRequest
func (_e *MockHandler_Expecter) MyInvites(ctx any, req any) *MockHandler_MyInvites_Call {
	return &MockHandler_MyInvites_Call{Call: _e.mock.On("MyInvites", ctx, req)}
}

func (_c *MockHandler_MyInvites_Call) Run(run func(ctx context.Context, req *dto.MyInvitesRequest)) *MockHandler_MyInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.MyInvitesRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.MyInvitesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_MyInvites_Call) Return(partyInvitesResponse *dto.PartyInvitesResponse, err error) *MockHandler_MyInvites_Call {
	_c.Call.Return(partyInvitesResponse, err)
	return _c
}

func (_c *MockHandler_MyInvites_Call) RunAndReturn(run func(ctx context.Context, req *dto.MyInvitesRequest) (*dto.PartyInvitesResponse, error)) *MockHandler_MyInvites_Call {
	_c.Call.Return(run)
	return _c
}

// MyParties provides a mock function for the type MockHandler
func (_mock *MockHandler) MyParties(ctx context.Context, req *dto.MyPartiesRequest) (*dto.PartiesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MyParties")
	}

	var r0 *dto.PartiesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.MyPartiesRequest) (*dto.PartiesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.MyPartiesRequest) *dto.PartiesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PartiesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.MyPartiesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_MyParties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyParties'
type MockHandler_MyParties_Call struct {
	*mock.Call
}

// MyParties is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.MyPartiesRequest
func (_e *MockHandler_Expecter) MyParties(ctx any, req any) *MockHandler_MyParties_Call {
	return &MockHandler_MyParties_Call{Call: _e.mock.On("MyParties", ctx, req)}
}

func (_c *MockHandler_MyParties_Call) Run(run func(ctx context.Context, req *dto.MyPartiesRequest)) *MockHandler_MyParties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.MyPartiesRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.MyPartiesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_MyParties_Call) Return(partiesResponse *dto.PartiesResponse, err error) *MockHandler_MyParties_Call {
	_c.Call.Return(partiesResponse, err)
	return _c
}

func (_c *MockHandler_MyParties_Call) RunAndReturn(run func(ctx context.Context, req *dto.MyPartiesRequest) (*dto.PartiesResponse, error)) *MockHandler_MyParties_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type MockHandler
func (_mock *MockHandler) RemoveMember(ctx context.Context, req *dto.RemovePartyMemberRequest) (*dto.RemovePartyMemberResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 *dto.RemovePartyMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RemovePartyMemberRequest) (*dto.RemovePartyMemberResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RemovePartyMemberRequest) *dto.RemovePartyMemberResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RemovePartyMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RemovePartyMemberRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockHandler_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RemovePartyMemberRequest
func (_e *MockHandler_Expecter) RemoveMember(ctx any, req any) *MockHandler_RemoveMember_Call {
	return &MockHandler_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, req)}
}

func (_c *MockHandler_RemoveMember_Call) Run(run func(ctx context.Context, req *dto.RemovePartyMemberRequest)) *MockHandler_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RemovePartyMemberRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.RemovePartyMemberRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_RemoveMember_Call) Return(removePartyMemberResponse *dto.RemovePartyMemberResponse, err error) *MockHandler_RemoveMember_Call {
	_c.Call.Return(removePartyMemberResponse, err)
	return _c
}

func (_c *MockHandler_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, req *dto.RemovePartyMemberRequest) (*dto.RemovePartyMemberResponse, error)) *MockHandler_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}
