// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_story

import (
	"context"
	"io"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, actorID string, partyID string, image io.Reader, size int64, contentType string, filename string) (entity.Story, error) {
	ret := _mock.Called(ctx, actorID, partyID, image, size, contentType, filename)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Story
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, string, string) (entity.Story, error)); ok {
		return returnFunc(ctx, actorID, partyID, image, size, contentType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, string, string) entity.Story); ok {
		r0 = returnFunc(ctx, actorID, partyID, image, size, contentType, filename)
	} else {
		r0 = ret.Get(0).(entity.Story)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, int64, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, image, size, contentType, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - image io.Reader
//   - size int64
//   - contentType string
//   - filename string
func (_e *MockService_Expecter) Create(ctx any, actorID any, partyID any, image any, size any, contentType any, filename any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, actorID, partyID, image, size, contentType, filename)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, actorID string, partyID string, image io.Reader, size int64, contentType string, filename string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(story entity.Story, err error) *MockService_Create_Call {
	_c.Call.Return(story, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, image io.Reader, size int64, contentType string, filename string) (entity.Story, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, actorID string, partyID string, storyID string) error {
	ret := _mock.Called(ctx, actorID, partyID, storyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, partyID, storyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - storyID string
func (_e *MockService_Expecter) Delete(ctx any, actorID any, partyID any, storyID any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, actorID, partyID, storyID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, actorID string, partyID string, storyID string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, storyID string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockService
func (_mock *MockService) ListByUser(ctx context.Context, actorID string, partyID string, targetUserID string) ([]entity.Story, error) {
	ret := _mock.Called(ctx, actorID, partyID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.Story
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]entity.Story, error)); ok {
		return returnFunc(ctx, actorID, partyID, targetUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []entity.Story); ok {
		r0 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Story)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, partyID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockService_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - partyID string
//   - targetUserID string
func (_e *MockService_Expecter) ListByUser(ctx any, actorID any, partyID any, targetUserID any) *MockService_ListByUser_Call {
	return &MockService_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, actorID, partyID, targetUserID)}
}

func (_c *MockService_ListByUser_Call) Run(run func(ctx context.Context, actorID string, partyID string, targetUserID string)) *MockService_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListByUser_Call) Return(storys []entity.Story, err error) *MockService_ListByUser_Call {
	_c.Call.Return(storys, err)
	return _c
}

func (_c *MockService_ListByUser_Call) RunAndReturn(run func(ctx context.Context, actorID string, partyID string, targetUserID string) ([]entity.Story, error)) *MockService_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
