// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_savedlocation

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(ctx context.Context, req *dto.CreateSavedLocationRequest) (*dto.SavedLocationResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.SavedLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateSavedLocationRequest) (*dto.SavedLocationResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateSavedLocationRequest) *dto.SavedLocationResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SavedLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateSavedLocationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateSavedLocationRequest
func (_e *MockHandler_Expecter) Create(ctx any, req any) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockHandler_Create_Call) Run(run func(ctx context.Context, req *dto.CreateSavedLocationRequest)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateSavedLocationRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateSavedLocationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return(savedLocationResponse *dto.SavedLocationResponse, err error) *MockHandler_Create_Call {
	_c.Call.Return(savedLocationResponse, err)
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(ctx context.Context, req *dto.CreateSavedLocationRequest) (*dto.SavedLocationResponse, error)) *MockHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHandler
func (_mock *MockHandler) Delete(ctx context.Context, req *dto.DeleteSavedLocationRequest) (*dto.DeleteSavedLocationResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *dto.DeleteSavedLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteSavedLocationRequest) (*dto.DeleteSavedLocationResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DeleteSavedLocationRequest) *dto.DeleteSavedLocationResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteSavedLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.DeleteSavedLocationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.DeleteSavedLocationRequest
func (_e *MockHandler_Expecter) Delete(ctx any, req any) *MockHandler_Delete_Call {
	return &MockHandler_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockHandler_Delete_Call) Run(run func(ctx context.Context, req *dto.DeleteSavedLocationRequest)) *MockHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.DeleteSavedLocationRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.DeleteSavedLocationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Delete_Call) Return(deleteSavedLocationResponse *dto.DeleteSavedLocationResponse, err error) *MockHandler_Delete_Call {
	_c.Call.Return(deleteSavedLocationResponse, err)
	return _c
}

func (_c *MockHandler_Delete_Call) RunAndReturn(run func(ctx context.Context, req *dto.DeleteSavedLocationRequest) (*dto.DeleteSavedLocationResponse, error)) *MockHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockHandler
func (_mock *MockHandler) Get(ctx context.Context, req *dto.GetSavedLocationRequest) (*dto.SavedLocationResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.SavedLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetSavedLocationRequest) (*dto.SavedLocationResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetSavedLocationRequest) *dto.SavedLocationResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SavedLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.GetSavedLocationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.GetSavedLocationRequest
func (_e *MockHandler_Expecter) Get(ctx any, req any) *MockHandler_Get_Call {
	return &MockHandler_Get_Call{Call: _e.mock.On("Get", ctx, req)}
}

func (_c *MockHandler_Get_Call) Run(run func(ctx context.Context, req *dto.GetSavedLocationRequest)) *MockHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.GetSavedLocationRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.GetSavedLocationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Get_Call) Return(savedLocationResponse *dto.SavedLocationResponse, err error) *MockHandler_Get_Call {
	_c.Call.Return(savedLocationResponse, err)
	return _c
}

func (_c *MockHandler_Get_Call) RunAndReturn(run func(ctx context.Context, req *dto.GetSavedLocationRequest) (*dto.SavedLocationResponse, error)) *MockHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockHandler
func (_mock *MockHandler) List(ctx context.Context, req *dto.ListSavedLocationsRequest) (*dto.SavedLocationsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.SavedLocationsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListSavedLocationsRequest) (*dto.SavedLocationsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListSavedLocationsRequest) *dto.SavedLocationsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SavedLocationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.ListSavedLocationsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListSavedLocationsRequest
func (_e *MockHandler_Expecter) List(ctx any, req any) *MockHandler_List_Call {
	return &MockHandler_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockHandler_List_Call) Run(run func(ctx context.Context, req *dto.ListSavedLocationsRequest)) *MockHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ListSavedLocationsRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.ListSavedLocationsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_List_Call) Return(savedLocationsResponse *dto.SavedLocationsResponse, err error) *MockHandler_List_Call {
	_c.Call.Return(savedLocationsResponse, err)
	return _c
}

func (_c *MockHandler_List_Call) RunAndReturn(run func(ctx context.Context, req *dto.ListSavedLocationsRequest) (*dto.SavedLocationsResponse, error)) *MockHandler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockHandler
func (_mock *MockHandler) Update(ctx context.Context, req *dto.UpdateSavedLocationRequest) (*dto.SavedLocationResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.SavedLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateSavedLocationRequest) (*dto.SavedLocationResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateSavedLocationRequest) *dto.SavedLocationResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SavedLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UpdateSavedLocationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.UpdateSavedLocationRequest
func (_e *MockHandler_Expecter) Update(ctx any, req any) *MockHandler_Update_Call {
	return &MockHandler_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockHandler_Update_Call) Run(run func(ctx context.Context, req *dto.UpdateSavedLocationRequest)) *MockHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UpdateSavedLocationRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UpdateSavedLocationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Update_Call) Return(savedLocationResponse *dto.SavedLocationResponse, err error) *MockHandler_Update_Call {
	_c.Call.Return(savedLocationResponse, err)
	return _c
}

func (_c *MockHandler_Update_Call) RunAndReturn(run func(ctx context.Context, req *dto.UpdateSavedLocationRequest) (*dto.SavedLocationResponse, error)) *MockHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
