// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_upload

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// UploadImage provides a mock function for the type MockService
func (_mock *MockService) UploadImage(ctx context.Context, image io.Reader, size int64, contentType string, filename string) (string, error) {
	ret := _mock.Called(ctx, image, size, contentType, filename)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int64, string, string) (string, error)); ok {
		return returnFunc(ctx, image, size, contentType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int64, string, string) string); ok {
		r0 = returnFunc(ctx, image, size, contentType, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, int64, string, string) error); ok {
		r1 = returnFunc(ctx, image, size, contentType, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type MockService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image io.Reader
//   - size int64
//   - contentType string
//   - filename string
func (_e *MockService_Expecter) UploadImage(ctx any, image any, size any, contentType any, filename any) *MockService_UploadImage_Call {
	return &MockService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, image, size, contentType, filename)}
}

func (_c *MockService_UploadImage_Call) Run(run func(ctx context.Context, image io.Reader, size int64, contentType string, filename string)) *MockService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_UploadImage_Call) Return(s string, err error) *MockService_UploadImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_UploadImage_Call) RunAndReturn(run func(ctx context.Context, image io.Reader, size int64, contentType string, filename string) (string, error)) *MockService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}
