// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_position

import (
	"context"

	"github.com/fark-tee/fark-tee-backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, position entity.Position) (entity.Position, error) {
	ret := _mock.Called(ctx, position)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Position) (entity.Position, error)); ok {
		return returnFunc(ctx, position)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Position) entity.Position); ok {
		r0 = returnFunc(ctx, position)
	} else {
		r0 = ret.Get(0).(entity.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Position) error); ok {
		r1 = returnFunc(ctx, position)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - position entity.Position
func (_e *MockRepository_Expecter) Create(ctx any, position any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, position)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, position entity.Position)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Position
		if args[1] != nil {
			arg1 = args[1].(entity.Position)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(position1 entity.Position, err error) *MockRepository_Create_Call {
	_c.Call.Return(position1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, position entity.Position) (entity.Position, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByPartyID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindLatestByPartyID(ctx context.Context, partyID string) ([]entity.Position, error) {
	ret := _mock.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByPartyID")
	}

	var r0 []entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Position, error)); ok {
		return returnFunc(ctx, partyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Position); ok {
		r0 = returnFunc(ctx, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindLatestByPartyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByPartyID'
type MockRepository_FindLatestByPartyID_Call struct {
	*mock.Call
}

// FindLatestByPartyID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
func (_e *MockRepository_Expecter) FindLatestByPartyID(ctx any, partyID any) *MockRepository_FindLatestByPartyID_Call {
	return &MockRepository_FindLatestByPartyID_Call{Call: _e.mock.On("FindLatestByPartyID", ctx, partyID)}
}

func (_c *MockRepository_FindLatestByPartyID_Call) Run(run func(ctx context.Context, partyID string)) *MockRepository_FindLatestByPartyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindLatestByPartyID_Call) Return(positions []entity.Position, err error) *MockRepository_FindLatestByPartyID_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockRepository_FindLatestByPartyID_Call) RunAndReturn(run func(ctx context.Context, partyID string) ([]entity.Position, error)) *MockRepository_FindLatestByPartyID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByPartyIDAndUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindLatestByPartyIDAndUserID(ctx context.Context, partyID string, userID string) (entity.Position, error) {
	ret := _mock.Called(ctx, partyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByPartyIDAndUserID")
	}

	var r0 entity.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.Position, error)); ok {
		return returnFunc(ctx, partyID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.Position); ok {
		r0 = returnFunc(ctx, partyID, userID)
	} else {
		r0 = ret.Get(0).(entity.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, partyID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindLatestByPartyIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByPartyIDAndUserID'
type MockRepository_FindLatestByPartyIDAndUserID_Call struct {
	*mock.Call
}

// FindLatestByPartyIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - userID string
func (_e *MockRepository_Expecter) FindLatestByPartyIDAndUserID(ctx any, partyID any, userID any) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	return &MockRepository_FindLatestByPartyIDAndUserID_Call{Call: _e.mock.On("FindLatestByPartyIDAndUserID", ctx, partyID, userID)}
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) Run(run func(ctx context.Context, partyID string, userID string)) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) Return(position entity.Position, err error) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Return(position, err)
	return _c
}

func (_c *MockRepository_FindLatestByPartyIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, partyID string, userID string) (entity.Position, error)) *MockRepository_FindLatestByPartyIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}
