// Code generated by go-wireset-gen. DO NOT EDIT.

package di

import (
	config "github.com/fark-tee/fark-tee-backend/internal/config"
	handler "github.com/fark-tee/fark-tee-backend/internal/handler"
	devicetoken "github.com/fark-tee/fark-tee-backend/internal/handler/devicetoken"
	googleoauth "github.com/fark-tee/fark-tee-backend/internal/handler/googleoauth"
	party "github.com/fark-tee/fark-tee-backend/internal/handler/party"
	review "github.com/fark-tee/fark-tee-backend/internal/handler/review"
	savedlocation "github.com/fark-tee/fark-tee-backend/internal/handler/savedlocation"
	story "github.com/fark-tee/fark-tee-backend/internal/handler/story"
	trip "github.com/fark-tee/fark-tee-backend/internal/handler/trip"
	upload "github.com/fark-tee/fark-tee-backend/internal/handler/upload"
	user "github.com/fark-tee/fark-tee-backend/internal/handler/user"
	context "github.com/fark-tee/fark-tee-backend/internal/infrastructure/context"
	database "github.com/fark-tee/fark-tee-backend/internal/infrastructure/database"
	fcm "github.com/fark-tee/fark-tee-backend/internal/infrastructure/fcm"
	googleoauth2 "github.com/fark-tee/fark-tee-backend/internal/infrastructure/googleoauth"
	logger "github.com/fark-tee/fark-tee-backend/internal/infrastructure/logger"
	osrm "github.com/fark-tee/fark-tee-backend/internal/infrastructure/osrm"
	storage "github.com/fark-tee/fark-tee-backend/internal/infrastructure/storage"
	token "github.com/fark-tee/fark-tee-backend/internal/infrastructure/token"
	authmw "github.com/fark-tee/fark-tee-backend/internal/middleware/authmw"
	devicetoken3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/devicetoken"
	party3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/party"
	partymember "github.com/fark-tee/fark-tee-backend/internal/repository/database/partymember"
	position "github.com/fark-tee/fark-tee-backend/internal/repository/database/position"
	review3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/review"
	savedlocation3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/savedlocation"
	story3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/story"
	trip3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/trip"
	user3 "github.com/fark-tee/fark-tee-backend/internal/repository/database/user"
	auth "github.com/fark-tee/fark-tee-backend/internal/service/auth"
	devicetoken2 "github.com/fark-tee/fark-tee-backend/internal/service/devicetoken"
	party2 "github.com/fark-tee/fark-tee-backend/internal/service/party"
	review2 "github.com/fark-tee/fark-tee-backend/internal/service/review"
	savedlocation2 "github.com/fark-tee/fark-tee-backend/internal/service/savedlocation"
	story2 "github.com/fark-tee/fark-tee-backend/internal/service/story"
	trip2 "github.com/fark-tee/fark-tee-backend/internal/service/trip"
	upload2 "github.com/fark-tee/fark-tee-backend/internal/service/upload"
	user2 "github.com/fark-tee/fark-tee-backend/internal/service/user"

	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	config.New,
)

var HandlerSet = wire.NewSet(
	handler.NewHandlers,
	devicetoken.New,
	googleoauth.New,
	party.New,
	review.New,
	savedlocation.New,
	story.New,
	trip.New,
	upload.New,
	user.New,
)

var InfrastructureSet = wire.NewSet(
	context.NewContext,
	database.NewMongoClient,
	database.NewMongoDatabase,
	fcm.New,
	googleoauth2.NewVerifier,
	logger.NewLogger,
	osrm.NewClient,
	storage.NewUploader,
	token.NewManager,
	authmw.New,
)

var RepositorySet = wire.NewSet(
	devicetoken3.New,
	party3.New,
	partymember.New,
	position.New,
	review3.New,
	savedlocation3.New,
	story3.New,
	trip3.New,
	user3.New,
)

var ServiceSet = wire.NewSet(
	auth.New,
	devicetoken2.New,
	party2.New,
	review2.New,
	savedlocation2.New,
	story2.New,
	trip2.New,
	upload2.New,
	user2.New,
)
