// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/fark-tee/fark-tee-backend/cmd/server/server"
	"github.com/fark-tee/fark-tee-backend/internal/config"
	"github.com/fark-tee/fark-tee-backend/internal/handler"
	instagramoauth2 "github.com/fark-tee/fark-tee-backend/internal/handler/instagramoauth"
	savedlocation3 "github.com/fark-tee/fark-tee-backend/internal/handler/savedlocation"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/context"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/database"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/instagramoauth"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/logger"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/savedlocation"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/user"
	"github.com/fark-tee/fark-tee-backend/internal/service/auth"
	savedlocation2 "github.com/fark-tee/fark-tee-backend/internal/service/savedlocation"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.NewLogger(configConfig)
	contextContext, cleanup := context.NewContext(slogLogger)
	client, cleanup2, err := database.NewMongoClient(contextContext, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mongoDatabase := database.NewMongoDatabase(client, configConfig)
	repository, err := user.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	verifier := instagramoauth.NewVerifier(configConfig)
	service := auth.New(repository, verifier)
	instagramoauthHandler := instagramoauth2.New(service)
	savedlocationRepository, err := savedlocation.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	savedlocationService := savedlocation2.New(savedlocationRepository)
	savedlocationHandler := savedlocation3.New(savedlocationService)
	handlers := handler.NewHandlers(instagramoauthHandler, savedlocationHandler)
	serverServer := server.New(configConfig, handlers)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
