// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/fark-tee/fark-tee-backend/cmd/server/server"
	"github.com/fark-tee/fark-tee-backend/internal/config"
	"github.com/fark-tee/fark-tee-backend/internal/handler"
	devicetoken3 "github.com/fark-tee/fark-tee-backend/internal/handler/devicetoken"
	googleoauth2 "github.com/fark-tee/fark-tee-backend/internal/handler/googleoauth"
	party3 "github.com/fark-tee/fark-tee-backend/internal/handler/party"
	review3 "github.com/fark-tee/fark-tee-backend/internal/handler/review"
	savedlocation3 "github.com/fark-tee/fark-tee-backend/internal/handler/savedlocation"
	story3 "github.com/fark-tee/fark-tee-backend/internal/handler/story"
	trip3 "github.com/fark-tee/fark-tee-backend/internal/handler/trip"
	upload2 "github.com/fark-tee/fark-tee-backend/internal/handler/upload"
	user3 "github.com/fark-tee/fark-tee-backend/internal/handler/user"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/context"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/database"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/fcm"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/googleoauth"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/logger"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/osrm"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/storage"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/token"
	"github.com/fark-tee/fark-tee-backend/internal/middleware/authmw"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/devicetoken"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/party"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/partymember"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/position"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/review"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/savedlocation"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/story"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/trip"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/user"
	"github.com/fark-tee/fark-tee-backend/internal/service/auth"
	devicetoken2 "github.com/fark-tee/fark-tee-backend/internal/service/devicetoken"
	party2 "github.com/fark-tee/fark-tee-backend/internal/service/party"
	review2 "github.com/fark-tee/fark-tee-backend/internal/service/review"
	savedlocation2 "github.com/fark-tee/fark-tee-backend/internal/service/savedlocation"
	story2 "github.com/fark-tee/fark-tee-backend/internal/service/story"
	trip2 "github.com/fark-tee/fark-tee-backend/internal/service/trip"
	"github.com/fark-tee/fark-tee-backend/internal/service/upload"
	user2 "github.com/fark-tee/fark-tee-backend/internal/service/user"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.NewLogger(configConfig)
	contextContext, cleanup := context.NewContext(slogLogger)
	client, cleanup2, err := database.NewMongoClient(contextContext, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mongoDatabase := database.NewMongoDatabase(client, configConfig)
	repository, err := user.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	verifier := googleoauth.NewVerifier(configConfig)
	manager := token.NewManager(configConfig)
	service := auth.New(configConfig, repository, verifier, manager)
	googleoauthHandler := googleoauth2.New(service)
	savedlocationRepository, err := savedlocation.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	savedlocationService := savedlocation2.New(savedlocationRepository)
	savedlocationHandler := savedlocation3.New(savedlocationService)
	partyRepository, err := party.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	partymemberRepository, err := partymember.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	devicetokenRepository, err := devicetoken.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fcmClient, err := fcm.New(contextContext, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	partyService := party2.New(partyRepository, partymemberRepository, repository, devicetokenRepository, fcmClient)
	partyHandler := party3.New(partyService)
	storyRepository, err := story.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploader, err := storage.NewUploader(contextContext, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	storyService := story2.New(storyRepository, partymemberRepository, uploader)
	storyHandler := story3.New(storyService)
	tripRepository, err := trip.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	positionRepository, err := position.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	osrmClient := osrm.NewClient(configConfig)
	tripService := trip2.New(partyRepository, partymemberRepository, tripRepository, positionRepository, repository, osrmClient)
	tripHandler := trip3.New(tripService)
	uploadService := upload.New(uploader)
	uploadHandler := upload2.New(uploadService)
	userService := user2.New(repository, uploader)
	userHandler := user3.New(userService)
	devicetokenService := devicetoken2.New(devicetokenRepository)
	devicetokenHandler := devicetoken3.New(devicetokenService)
	reviewRepository, err := review.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	reviewService := review2.New(reviewRepository, partymemberRepository, repository)
	reviewHandler := review3.New(reviewService)
	handlers := handler.NewHandlers(googleoauthHandler, savedlocationHandler, partyHandler, storyHandler, tripHandler, uploadHandler, userHandler, devicetokenHandler, reviewHandler)
	middleware := authmw.New(manager)
	serverServer := server.New(configConfig, handlers, middleware)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
