// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/fark-tee/fark-tee-backend/cmd/server/server"
	"github.com/fark-tee/fark-tee-backend/internal/config"
	"github.com/fark-tee/fark-tee-backend/internal/handler"
	instagramoauth2 "github.com/fark-tee/fark-tee-backend/internal/handler/instagramoauth"
	party3 "github.com/fark-tee/fark-tee-backend/internal/handler/party"
	savedlocation3 "github.com/fark-tee/fark-tee-backend/internal/handler/savedlocation"
	story3 "github.com/fark-tee/fark-tee-backend/internal/handler/story"
	trip3 "github.com/fark-tee/fark-tee-backend/internal/handler/trip"
	user3 "github.com/fark-tee/fark-tee-backend/internal/handler/user"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/context"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/database"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/instagramoauth"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/logger"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/storage"
	"github.com/fark-tee/fark-tee-backend/internal/infrastructure/token"
	"github.com/fark-tee/fark-tee-backend/internal/middleware/authmw"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/party"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/partymember"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/position"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/savedlocation"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/story"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/trip"
	"github.com/fark-tee/fark-tee-backend/internal/repository/database/user"
	"github.com/fark-tee/fark-tee-backend/internal/service/auth"
	party2 "github.com/fark-tee/fark-tee-backend/internal/service/party"
	savedlocation2 "github.com/fark-tee/fark-tee-backend/internal/service/savedlocation"
	story2 "github.com/fark-tee/fark-tee-backend/internal/service/story"
	trip2 "github.com/fark-tee/fark-tee-backend/internal/service/trip"
	user2 "github.com/fark-tee/fark-tee-backend/internal/service/user"
)

// Injectors from wire.go:

func Initialize() (*server.Server, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.NewLogger(configConfig)
	contextContext, cleanup := context.NewContext(slogLogger)
	client, cleanup2, err := database.NewMongoClient(contextContext, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mongoDatabase := database.NewMongoDatabase(client, configConfig)
	repository, err := user.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	verifier := instagramoauth.NewVerifier(configConfig)
	manager := token.NewManager(configConfig)
	service := auth.New(repository, verifier, manager)
	instagramoauthHandler := instagramoauth2.New(service)
	savedlocationRepository, err := savedlocation.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	savedlocationService := savedlocation2.New(savedlocationRepository)
	savedlocationHandler := savedlocation3.New(savedlocationService)
	partyRepository, err := party.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	partymemberRepository, err := partymember.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	partyService := party2.New(partyRepository, partymemberRepository, repository)
	partyHandler := party3.New(partyService)
	storyRepository, err := story.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploader, err := storage.NewUploader(contextContext, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	storyService := story2.New(storyRepository, partymemberRepository, uploader)
	storyHandler := story3.New(storyService)
	tripRepository, err := trip.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	positionRepository, err := position.New(contextContext, mongoDatabase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tripService := trip2.New(partyRepository, partymemberRepository, tripRepository, positionRepository)
	tripHandler := trip3.New(tripService)
	userService := user2.New(repository)
	userHandler := user3.New(userService)
	handlers := handler.NewHandlers(instagramoauthHandler, savedlocationHandler, partyHandler, storyHandler, tripHandler, userHandler)
	middleware := authmw.New(manager)
	serverServer := server.New(configConfig, handlers, middleware)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
